### PR TITLE
Ikarus regex

### PR DESCRIPTION
**Pull request by JavierBotella**

### CODE REVIEW

**Comment by zv** [comment]
This breaks `not-a-virus`  and `-Ransom`

**Comment by JavierBotella** [comment]
@zv it gets nice names there: 
```Ikarus     |   | Linux      |           |            | trojan                         |     Encoder.One | Trojan-Ransom.Linux.Encoder.One
Ikarus     | H |            |           |            | trojan                         |           Agent | Trojan-Ransom.MSIL.Agent
Ikarus     |   |            |           |            | trojan                         |           Locky | Trojan-Ransom.Script.Locky
Ikarus     |   |            |           |            | trojan                         |        WannaCry | Trojan-Ransom.WannaCry
Ikarus     |   | Windows    |           |            | trojan                         |          Gimemo | Trojan-Ransom.Win32.Gimemo
```

```Ikarus     |   |            |           |            |                                |          AdLoad | not-a-virus:AdWare.AdLoad
Ikarus     |   | Windows    |           |            |                                |          DomaIQ | not-a-virus:AdWare.Win32.DomaIQ
Ikarus     | H |            |           |            | downloader                     |           Agent | not-a-virus:Downloader.Agent
Ikarus     |   |            |           |            | spyware                        |        IphoneOS | not-a-virus:Monitor.IphoneOS
Ikarus     |   |            |           |            | greyware                       |       NetFilter | not-a-virus:NetTool.NetFilter
Ikarus     |   |            |           |            | browser_modifier               |         CrawBar | not-a-virus:WebToolbar.CrawBar
Ikarus     | H |            |           |            | browser_modifier               |           Agent | not-a-virus:WebToolbar.MSIL.Agent
Ikarus     |   | Windows    |           |            | browser_modifier               |         Cossder | not-a-virus:WebToolbar.Win32.Cossder
```

There is still pending the change for removing things like `Agent` from there.

**Comment by JavierBotella** [comment]
`not-a-virus` in master:

```Ikarus     | H |            |           |            |                                |          AdLoad | not-a-virus:AdWare.AdLoad
Ikarus     | H | Windows    |           |            |                                |          DomaIQ | not-a-virus:AdWare.Win32.DomaIQ
Ikarus     | H |            |           |            | downloader                     | not-a-virus:Dow | not-a-virus:Downloader.Agent
Ikarus     | H | iPhoneOS   |           |            | spyware                        | not-a-virus:Mon | not-a-virus:Monitor.IphoneOS
Ikarus     | H |            |           |            | greyware                       |       NetFilter | not-a-virus:NetTool.NetFilter
Ikarus     | H |            |           |            | browser_modifier               |         CrawBar | not-a-virus:WebToolbar.CrawBar
Ikarus     | H |            |           |            | browser_modifier               | not-a-virus:Web | not-a-virus:WebToolbar.MSIL.Agent
Ikarus     | H | Windows    |           |            | browser_modifier               |         Cossder | not-a-virus:WebToolbar.Win32.Cossder
```

**Comment by zv** [comment]
To be clear, this still isn't passing the tests.

**Pull request closed without merging**
